// <auto-generated />
using System;
using CampusMapAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusMapAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CampusMapAPI.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Building_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("building", (string)null);
                });

            modelBuilder.Entity("CampusMapAPI.Models.Hotspot", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Hotspot_ID");

                    b.Property<string>("IconType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Icon_Type");

                    b.Property<int?>("MediaId")
                        .HasColumnType("int")
                        .HasColumnName("Media_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Pitch")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<int?>("SceneId")
                        .HasColumnType("int")
                        .HasColumnName("Scene_ID");

                    b.Property<int?>("TargetSceneId")
                        .HasColumnType("int")
                        .HasColumnName("Target_Scene_ID");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<decimal?>("Yaw")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MediaId" }, "Media_ID_idx");

                    b.HasIndex(new[] { "SceneId" }, "Scene_ID_idx");

                    b.ToTable("hotspot", (string)null);
                });

            modelBuilder.Entity("CampusMapAPI.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Media_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Media_Type");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("URL");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("CampusMapAPI.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Scene_ID");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int")
                        .HasColumnName("Building_ID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("PreviewMediaId")
                        .HasColumnType("int")
                        .HasColumnName("Preview_Media_ID");

                    b.Property<string>("Scenecol")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("scenecol");

                    b.Property<decimal?>("StartHfov")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)")
                        .HasColumnName("Start_HFov");

                    b.Property<decimal?>("StartPitch")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)")
                        .HasColumnName("Start_Pitch");

                    b.Property<decimal?>("StartYaw")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)")
                        .HasColumnName("Start_Yaw");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingId" }, "Building_ID_idx");

                    b.HasIndex(new[] { "PreviewMediaId" }, "Preview_Media_ID_idx");

                    b.ToTable("scene", (string)null);
                });

            modelBuilder.Entity("CampusMapAPI.Models.Hotspot", b =>
                {
                    b.HasOne("CampusMapAPI.Models.Media", "Media")
                        .WithMany("Hotspots")
                        .HasForeignKey("MediaId")
                        .HasConstraintName("Media_ID");

                    b.HasOne("CampusMapAPI.Models.Scene", "Scene")
                        .WithMany("Hotspots")
                        .HasForeignKey("SceneId")
                        .HasConstraintName("Scene_ID");

                    b.Navigation("Media");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("CampusMapAPI.Models.Scene", b =>
                {
                    b.HasOne("CampusMapAPI.Models.Building", "Building")
                        .WithMany("Scenes")
                        .HasForeignKey("BuildingId")
                        .HasConstraintName("Building_ID");

                    b.HasOne("CampusMapAPI.Models.Media", "PreviewMedia")
                        .WithMany("Scenes")
                        .HasForeignKey("PreviewMediaId")
                        .HasConstraintName("Preview_Media_ID");

                    b.Navigation("Building");

                    b.Navigation("PreviewMedia");
                });

            modelBuilder.Entity("CampusMapAPI.Models.Building", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("CampusMapAPI.Models.Media", b =>
                {
                    b.Navigation("Hotspots");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("CampusMapAPI.Models.Scene", b =>
                {
                    b.Navigation("Hotspots");
                });
#pragma warning restore 612, 618
        }
    }
}
